pluginManagement {
    repositories {
        maven {
            name = 'AliyunPublic'
            url = 'https://maven.aliyun.com/repository/public'
        }
        maven {
            name = 'AliyunGradlePlugin'
            url = 'https://maven.aliyun.com/repository/gradle-plugin'
        }
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}

rootProject.name = 'stoneblock'